# Generated by Django 5.2.5 on 2025-08-21 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servermembership',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='servermembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servermembership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
